name = "onesync-music-distribution"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

pages_build_output_dir = ".next"

[env.production]
name = "onesync-music-distribution"

[env.preview]
name = "onesync-music-distribution-preview"
