export const MUSIC_GENRES = [
  "Alternative",
  "Alternative Rock",
  "Ambient",
  "Blues",
  "Blues Rock",
  "Bluegrass",
  "Breakbeat",
  "Chillout",
  "Classical",
  "Country",
  "Country Pop",
  "Country Rock",
  "Dance",
  "Dance Pop",
  "Deep House",
  "Disco",
  "Drum & Bass",
  "Dubstep",
  "EDM",
  "Electronic",
  "Electro House",
  "Experimental",
  "Folk",
  "Folk Pop",
  "Folk Rock",
  "Funk",
  "Garage",
  "Gospel",
  "Grunge",
  "Hard Rock",
  "Hardcore",
  "Hip Hop/Rap",
  "House",
  "Indie",
  "Indie Pop",
  "Indie Rock",
  "Jazz",
  "Jazz Fusion",
  "Latin",
  "Latin Pop",
  "Latin Rock",
  "Lounge",
  "Metal",
  "Metalcore",
  "Neo Soul",
  "New Age",
  "Pop",
  "Pop Punk",
  "Pop Rock",
  "Progressive",
  "Progressive Rock",
  "Psychedelic",
  "Punk",
  "Punk Rock",
  "R&B",
  "Reggae",
  "Reggaeton",
  "Rock",
  "Singer-Songwriter",
  "Soul",
  "Soundtrack",
  "Synthpop",
  "Techno",
  "Trance",
  "Trap",
  "Trip Hop",
  "World",
  "World Music",
]

// Expanded genre catalog (main + subgenres)
export const EXPANDED_GENRES: { main: string; subs: string[] }[] = [
  { main: "Pop", subs: ["Electropop", "Synthpop", "Dance Pop", "Teen Pop", "Indie Pop", "Hyperpop"] },
  { main: "Hip Hop/Rap", subs: ["Trap", "Boom Bap", "Drill", "Lo-fi Hip Hop", "Alternative Hip Hop", "Cloud Rap", "Gangsta Rap", "Old School Rap", "Contemporary R&B"] },
  { main: "Electronic", subs: ["House", "Deep House", "Tech House", "Progressive House", "Techno", "Trance", "Dubstep", "Drum & Bass", "Ambient", "Electronica"] },
  { main: "Rock", subs: ["Alternative Rock", "Indie Rock", "Hard Rock", "Punk Rock", "Garage Rock", "Psychedelic Rock", "Progressive Rock", "Grunge"] },
  { main: "R&B", subs: ["Contemporary R&B", "Neo Soul", "Alt R&B", "Quiet Storm"] },
  { main: "Jazz", subs: ["Smooth Jazz", "Bebop", "Jazz Fusion", "Vocal Jazz", "Contemporary Jazz"] },
  { main: "Country", subs: ["Country Pop", "Country Rock", "Bluegrass", "Americana", "Alt Country"] },
  { main: "Latin", subs: ["Reggaeton", "Bachata", "Salsa", "Latin Pop", "Latin Trap", "Regional Mexican"] },
  { main: "Metal", subs: ["Heavy Metal", "Metalcore", "Death Metal", "Black Metal", "Doom Metal", "Nu Metal"] },
  { main: "Classical", subs: ["Baroque", "Romantic", "Contemporary", "Chamber Music", "Opera"] },
  { main: "Folk", subs: ["Indie Folk", "Contemporary Folk", "Celtic", "Singer-Songwriter"] },
  { main: "Reggae", subs: ["Roots Reggae", "Dancehall", "Dub", "Rocksteady"] },
  { main: "World", subs: ["Afrobeats", "K-Pop", "J-Pop", "C-Pop", "Afrobeat", "Highlife"] },
]

export const MUSIC_STORES = [
  "Spotify",
  "Apple Music",
  "YouTube Music",
  "Amazon Music",
  "Deezer",
  "Tidal",
  "Pandora",
  "SoundCloud",
  "Bandcamp",
  "Beatport",
  "Traxsource",
  "Juno Download",
  "7digital",
  "Qobuz",
  "Napster",
  "iHeartRadio",
  "Shazam",
  "Anghami",
  "JOOX",
  "NetEase Cloud Music",
  "TikTok",
  "Facebook/Instagram",
  "Twitch",
  "Audiomack",
]

export const LANGUAGES = [
  { code: "en", name: "English" },
  { code: "es", name: "Spanish" },
  { code: "fr", name: "French" },
  { code: "de", name: "German" },
  { code: "it", name: "Italian" },
  { code: "pt", name: "Portuguese" },
  { code: "ja", name: "Japanese" },
  { code: "ko", name: "Korean" },
  { code: "zh", name: "Chinese" },
  { code: "ar", name: "Arabic" },
  { code: "hi", name: "Hindi" },
  { code: "ru", name: "Russian" },
]

export const RELEASE_TYPES = ["Single", "EP", "Album"]

// Price tiers for singles
export const SINGLE_PRICE_TIERS = [
  { id: "0.79", name: "$0.79", price: 0.79, description: "Budget pricing for singles" },
  { id: "0.99", name: "$0.99", price: 0.99, description: "Standard pricing for singles" },
  { id: "1.29", name: "$1.29", price: 1.29, description: "Premium pricing for singles" },
]

// Price tiers for albums  
export const ALBUM_PRICE_TIERS = [
  { id: "7.99", name: "$7.99", price: 7.99, description: "Budget pricing for albums" },
  { id: "9.99", name: "$9.99", price: 9.99, description: "Standard pricing for albums" },
  { id: "11.99", name: "$11.99", price: 11.99, description: "Premium pricing for albums" },
  { id: "12.99", name: "$12.99", price: 12.99, description: "Deluxe pricing for albums" },
]

// Legacy price tiers (keeping for compatibility)
export const PRICE_TIERS = [
  { id: "0.99", name: "$0.99", price: 0.99, description: "Standard pricing" },
  { id: "1.29", name: "$1.29", price: 1.29, description: "Premium pricing" },
  { id: "custom", name: "Custom", price: 0, description: "Set your own price" },
]
